apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: characteristic-bee-nodejs 
  janus-idp.io/tekton: characteristic-bee-nodejs
  backstage.io/kubernetes-id: characteristic-bee-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: characteristic-bee-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  